#use "./stationDistanceType.ml";;

let stationDistances = [
  {start = "yoyogiuehara"; finish = "yoyogikouen"; transit = "chiyodaline"; distance = 1.0; time = 2};
  {start = "yoyogikouen"; finish = "meijijinguumae"; transit = "chiyodaline"; distance = 1.2; time = 2};
  {start = "meijijinguumae"; finish = "omotesandou"; transit = "chiyodaline"; distance = 0.9; time = 2};
  {start = "omotesandou"; finish = "nogizaka"; transit = "chiyodaline"; distance = 1.4; time = 3};
  {start = "nogizaka"; finish = "akasaka"; transit = "chiyodaline"; distance = 1.1; time = 2};
  {start = "akasaka"; finish = "akokkaigijidoumae"; transit = "chiyodaline"; distance = 0.8; time = 1};
  {start = "akokkaigijidoumae"; finish = "kasumigaseki"; transit = "chiyodaline"; distance = 0.7; time = 1};
  {start = "kasumigaseki"; finish = "hibiya"; transit = "chiyodaline"; distance = 1.2; time = 2};
  {start = "hibiya"; finish = "nijuubasimae"; transit = "chiyodaline"; distance = 0.7; time = 1};
  {start = "nijuubasimae"; finish = "otemachi"; transit = "chiyodaline"; distance = 0.7; time = 1};
  {start = "otemachi"; finish = "shin-ochanomizu"; transit = "chiyodaline"; distance = 1.3; time = 2};
  {start = "shin-ochanomizu"; finish = "yushima"; transit = "chiyodaline"; distance = 1.2; time = 2};
  {start = "yushima"; finish = "nedu"; transit = "chiyodaline"; distance = 1.2; time = 2};
  {start = "nedu"; finish = "sendagi"; transit = "chiyodaline"; distance = 1.0; time = 2};
  {start = "sendagi"; finish = "nishinippori"; transit = "chiyodaline"; distance = 0.9; time = 1};
  {start = "nishinippori"; finish = "machiya"; transit = "chiyodaline"; distance = 1.7; time = 2};
  {start = "machiya"; finish = "kitasenjyu"; transit = "chiyodaline"; distance = 2.6; time = 3};
  {start = "kitasenjyu"; finish = "ayase"; transit = "chiyodaline"; distance = 2.5; time = 3};
  {start = "ayase"; finish = "kitaayase"; transit = "chiyodaline"; distance = 2.1; time = 4};
  {start = "asakusa"; finish = "tawaramachi"; transit = "ginzaline"; distance = 0.8; time = 2};
  {start = "tawaramachi"; finish = "inaricho"; transit = "ginzaline"; distance = 0.7; time = 1};
  {start = "inaricho"; finish = "ueno"; transit = "ginzaline"; distance = 0.7; time = 2};
  {start = "ueno"; finish = "uenohirokoji"; transit = "ginzaline"; distance = 0.5; time = 2};
  {start = "uenohirokoji"; finish = "suehirocho"; transit = "ginzaline"; distance = 0.6; time = 1};
  {start = "suehirocho"; finish = "kanda"; transit = "ginzaline"; distance = 1.1; time = 2};
  {start = "kanda"; finish = "mitsukoshimae"; transit = "ginzaline"; distance = 0.7; time = 1};
  {start = "mitsukoshimae"; finish = "nihonbashi"; transit = "ginzaline"; distance = 0.6; time = 2};
  {start = "nihonbashi"; finish = "kyobashi"; transit = "ginzaline"; distance = 0.7; time = 2};
  {start = "kyobashi"; finish = "ginza"; transit = "ginzaline"; distance = 0.7; time = 1};
  {start = "ginza"; finish = "shinbashi"; transit = "ginzaline"; distance = 0.9; time = 2};
  {start = "shinbashi"; finish = "toranomon"; transit = "ginzaline"; distance = 0.8; time = 2};
  {start = "toranomon"; finish = "tameikesannou"; transit = "ginzaline"; distance = 0.6; time = 2};
  {start = "tameikesannou"; finish = "akasakamitsuke"; transit = "ginzaline"; distance = 0.9; time = 2};
  {start = "akasakamitsuke"; finish = "aoyamaicchome"; transit = "ginzaline"; distance = 1.3; time = 2};
  {start = "aoyamaicchome"; finish = "gaienmae"; transit = "ginzaline"; distance = 0.7; time = 2};
  {start = "gaienmae"; finish = "omotesandou"; transit = "ginzaline"; distance = 0.7; time = 1};
  {start = "omotesandou"; finish = "shibuya"; transit = "ginzaline"; distance = 1.3; time = 1};
  {start = "shibuya"; finish = "omotesandou"; transit = "hannzoumonline"; distance = 1.3; time = 2};
  {start = "omotesandou"; finish = "aoyamaicchome"; transit = "hannzoumonline"; distance = 1.4; time = 2};
  {start = "aoyamaicchome"; finish = "nagatacho"; transit = "hannzoumonline"; distance = 1.3; time = 2};
  {start = "nagatacho"; finish = "hanzomon"; transit = "hannzoumonline"; distance = 1.0; time = 2};
  {start = "hanzomon"; finish = "kudanshita"; transit = "hannzoumonline"; distance = 1.6; time = 2};
  {start = "kudanshita"; finish = "jinbocho"; transit = "hannzoumonline"; distance = 0.4; time = 1};
  {start = "jinbocho"; finish = "otemachi"; transit = "hannzoumonline"; distance = 1.7; time = 3};
  {start = "otemachi"; finish = "mitsukoshimae"; transit = "hannzoumonline"; distance = 0.7; time = 1};
  {start = "mitsukoshimae"; finish = "suitengumae"; transit = "hannzoumonline"; distance = 1.3; time = 2};
  {start = "suitengumae"; finish = "kiyosumi-shirakawa"; transit = "hannzoumonline"; distance = 1.7; time = 3};
  {start = "kiyosumi-shirakawa"; finish = "sumiyoshi"; transit = "hannzoumonline"; distance = 1.9; time = 3};
  {start = "sumiyoshi"; finish = "kinshicho"; transit = "hannzoumonline"; distance = 1.; time = 2};
  {start = "kinshicho"; finish = "oshiage"; transit = "hannzoumonline"; distance = 1.4; time = 2};
  {start = "nakameguro"; finish = "ebisu"; transit = "hibiyaline"; distance = 1.; time = 2};
  {start = "ebisu"; finish = "hiro"; transit = "hibiyaline"; distance = 1.5; time = 3};
  {start = "hiro"; finish = "roppongi"; transit = "hibiyaline"; distance = 1.7; time = 3};
  {start = "roppongi"; finish = "kamiyacho"; transit = "hibiyaline"; distance = 1.5; time = 3};
  {start = "kamiyacho"; finish = "kasumigaseki"; transit = "hibiyaline"; distance = 1.3; time = 2};
  {start = "kasumigaseki"; finish = "hibiya"; transit = "hibiyaline"; distance = 1.2; time = 2};
  {start = "hibiya"; finish = "ginza"; transit = "hibiyaline"; distance = 0.4; time = 1};
  {start = "ginza"; finish = "higashiginza"; transit = "hibiyaline"; distance = 0.4; time = 1};
  {start = "higashiginza"; finish = "tsukiji"; transit = "hibiyaline"; distance = 0.6; time = 2};
  {start = "tsukiji"; finish = "hacchobori"; transit = "hibiyaline"; distance = 1.; time = 2};
  {start = "hacchobori"; finish = "kayabacho"; transit = "hibiyaline"; distance = 0.5; time = 1};
  {start = "kayabacho"; finish = "ningyomachi"; transit = "hibiyaline"; distance = 0.9; time = 2};
  {start = "ningyomachi"; finish = "kodemmacho"; transit = "hibiyaline"; distance = 0.6; time = 1};
  {start = "kodemmacho"; finish = "akihabara"; transit = "hibiyaline"; distance = 0.9; time = 2};
  {start = "akihabara"; finish = "nakaokachimachi"; transit = "hibiyaline"; distance = 1.; time = 1};
  {start = "nakaokachimachi"; finish = "ueno"; transit = "hibiyaline"; distance = 0.5; time = 1};
  {start = "ueno"; finish = "iriya"; transit = "hibiyaline"; distance = 1.2; time = 2};
  {start = "iriya"; finish = "minowa"; transit = "hibiyaline"; distance = 1.2; time = 2};
  {start = "minowa"; finish = "minamisenju"; transit = "hibiyaline"; distance = 0.8; time = 2};
  {start = "minamisenju"; finish = "kitasenjyu"; transit = "hibiyaline"; distance = 1.8; time = 3};
  {start = "ikebukuro"; finish = "shinotsuka"; transit = "marunouchiline"; distance = 1.8; time = 3};
  {start = "shinotsuka"; finish = "myogadani"; transit = "marunouchiline"; distance = 1.2; time = 2};
  {start = "myogadani"; finish = "korakuen"; transit = "marunouchiline"; distance = 1.8; time = 2};
  {start = "korakuen"; finish = "hongosanchome"; transit = "marunouchiline"; distance = 0.8; time = 1};
  {start = "hongosanchome"; finish = "ochanomizu"; transit = "marunouchiline"; distance = 0.8; time = 1};
  {start = "ochanomizu"; finish = "awajicho"; transit = "marunouchiline"; distance = 0.8; time = 1};
  {start = "awajicho"; finish = "otemachi"; transit = "marunouchiline"; distance = 0.9; time = 2};
  {start = "otemachi"; finish = "tokyo"; transit = "marunouchiline"; distance = 0.6; time = 1};
  {start = "tokyo"; finish = "ginza"; transit = "marunouchiline"; distance = 1.1; time = 2};
  {start = "ginza"; finish = "kasumigaseki"; transit = "marunouchiline"; distance = 1.0; time = 2};
  {start = "kasumigaseki"; finish = "akokkaigijidoumae"; transit = "marunouchiline"; distance = 0.7; time = 1};
  {start = "akokkaigijidoumae"; finish = "akasakamitsuke"; transit = "marunouchiline"; distance = 0.9; time = 2};
  {start = "akasakamitsuke"; finish = "yotsuya"; transit = "marunouchiline"; distance = 1.3; time = 2};
  {start = "yotsuya"; finish = "yotsuyasanchome"; transit = "marunouchiline"; distance = 1.0; time = 2};
  {start = "yotsuyasanchome"; finish = "shinjuku-gyoemmae"; transit = "marunouchiline"; distance = 0.9; time = 1};
  {start = "shinjuku-gyoemmae"; finish = "shinjuku-sanchome"; transit = "marunouchiline"; distance = 0.7; time = 1};
  {start = "shinjuku-sanchome"; finish = "shinjuku"; transit = "marunouchiline"; distance = 0.3; time = 1};
  {start = "shinjuku"; finish = "nishi-shinjuku"; transit = "marunouchiline"; distance = 0.8; time = 1};
  {start = "nishi-shinjuku"; finish = "nakano-sakaue"; transit = "marunouchiline"; distance = 1.1; time = 2};
  {start = "nakano-sakaue"; finish = "shin-nakano"; transit = "marunouchiline"; distance = 1.1; time = 2};
  {start = "shin-nakano"; finish = "higashi-koenji"; transit = "marunouchiline"; distance = 1.0; time = 1};
  {start = "higashi-koenji"; finish = "shin-koenji"; transit = "marunouchiline"; distance = 0.9; time = 1};
  {start = "shin-koenji"; finish = "minami-asagaya"; transit = "marunouchiline"; distance = 1.2; time = 2};
  {start = "minami-asagaya"; finish = "ogikubo"; transit = "marunouchiline"; distance = 1.5; time = 2};
  {start = "nakano-sakaue"; finish = "nakano-shimbashi"; transit = "marunouchiline"; distance = 1.3; time = 2};
  {start = "nakano-shimbashi"; finish = "nakano-fujimicho"; transit = "marunouchiline"; distance = 0.6; time = 1};
  {start = "nakano-fujimicho"; finish = "honancho"; transit = "marunouchiline"; distance = 1.3; time = 2};
  {start = "ichigaya"; finish = "yotsuya"; transit = "nanbokuline"; distance = 1.0; time = 2};
  {start = "yotsuya"; finish = "nagatacho"; transit = "nanbokuline"; distance = 1.3; time = 3};
  {start = "nagatacho"; finish = "tameikesannou"; transit = "nanbokuline"; distance = 0.9; time = 1};
  {start = "tameikesannou"; finish = "roppongiitchome"; transit = "nanbokuline"; distance = 0.9; time = 2};
  {start = "roppongiitchome"; finish = "razabujuban"; transit = "nanbokuline"; distance = 1.2; time = 2};
  {start = "razabujuban"; finish = "rshirokanetakanawa"; transit = "nanbokuline"; distance = 1.3; time = 2};
  {start = "rshirokanetakanawa"; finish = "shirokanedai"; transit = "nanbokuline"; distance = 1.0; time = 2};
  {start = "shirokanedai"; finish = "meguro"; transit = "nanbokuline"; distance = 1.3; time = 2};
  {start = "ichigaya"; finish = "idabashi"; transit = "nanbokuline"; distance = 1.1 ; time = 2};
  {start = "idabashi"; finish = "korakuen"; transit = "nanbokuline"; distance = 1.4 ; time = 2};
  {start = "korakuen"; finish = "todaimae"; transit = "nanbokuline"; distance = 1.3 ; time = 3};
  {start = "todaimae"; finish = "honkomagome"; transit = "nanbokuline"; distance = 0.9 ; time = 2};
  {start = "honkomagome"; finish = "komagome"; transit = "nanbokuline"; distance = 1.4; time = 2};
  {start = "komagome"; finish = "nishigahara"; transit = "nanbokuline"; distance = 1.4; time = 2};
  {start = "nishigahara"; finish = "oji"; transit = "nanbokuline"; distance = 1.0; time = 2};
  {start = "oji"; finish = "ojikamiya"; transit = "nanbokuline"; distance = 1.2; time = 2};
  {start = "ojikamiya"; finish = "shimo"; transit = "nanbokuline"; distance = 1.6; time = 3};
  {start = "shimo"; finish = "akabaneiwabuchi"; transit = "nanbokuline"; distance = 1.1; time = 2};
  {start = "nishi-funabashi" ; finish = "baraki-nakayama"; transit = "tozailine"; distance = 1.9; time = 3};
  {start = "baraki-nakayama"; finish = "myoden"; transit = "tozailine"; distance = 2.1 ; time = 2};
  {start = "myoden"; finish = "gyotoku"; transit = "tozailine"; distance = 1.3 ; time = 2};
  {start = "gyotoku"; finish = "minami-gyotoku"; transit = "tozailine"; distance = 1.5 ; time = 2};
  {start = "minami-gyotoku"; finish = "urayasu" ; transit = "tozailine"; distance = 1.2 ; time = 2};
  {start = "urayasu" ; finish = "kasai"; transit = "tozailine"; distance = 1.9 ; time = 2};
  {start = "kasai"; finish = "nishi-kasai"; transit = "tozailine"; distance = 1.2 ; time = 2};
  {start = "nishi-kasai"; finish = "minami-sunamachi"; transit = "tozailine"; distance = 2.7 ; time = 2};
  {start = "minami-sunamachi"; finish = "touyoucho"; transit = "tozailine"; distance = 1.2 ; time = 2};
  {start = "touyoucho"; finish = "kiba" ; transit = "tozailine"; distance = 0.9 ; time = 1};
  {start = "kiba"; finish = "monzen-nakacho"; transit = "tozailine"; distance = 1.1 ; time = 1};
  {start = "monzen-nakacho"; finish = "kayabacho"; transit = "tozailine"; distance = 1.8 ; time = 2};
  {start = "kayabacho"; finish = "nihonbashi"; transit = "tozailine"; distance = 0.5 ; time = 1};
  {start = "nihonbashi"; finish = "otemachi"; transit = "tozailine"; distance = 0.8 ; time = 1};
  {start = "otemachi"; finish = "takebashi"; transit = "tozailine"; distance = 1.0; time = 2};
  {start = "takebashi"; finish = "kudanshita"; transit = "tozailine"; distance = 1.0; time = 1};
  {start = "kudanshita"; finish = "idabashi"; transit = "tozailine"; distance = 0.7; time = 1};
  {start = "idabashi"; finish = "kagurazaka"; transit = "tozailine"; distance = 1.2; time = 2};
  {start = "kagurazaka"; finish = "waseda"; transit = "tozailine"; distance = 1.2; time = 2};
  {start = "waseda"; finish = "takadanobaba"; transit = "tozailine"; distance = 1.7; time = 3};
  {start = "takadanobaba"; finish = "ochiai"; transit = "tozailine"; distance = 1.9; time = 3};
  {start = "ochiai"; finish = "nakano"; transit = "tozailine"; distance = 2.0; time = 3};
  {start = "shinkiba"; finish = "tatsumi"; transit = "yuurakucyoline"; distance = 1.5; time = 2};
  {start = "tatsumi"; finish = "toyosu"; transit = "yuurakucyoline"; distance = 1.7; time = 2};
  {start = "toyosu"; finish = "tsukishima"; transit = "yuurakucyoline"; distance = 1.4; time = 2};
  {start = "tsukishima"; finish = "shintomityou"; transit = "yuurakucyoline"; distance = 1.3; time = 2};
  {start = "shintomityou"; finish = "ginzaittyoume"; transit = "yuurakucyoline"; distance = 0.7; time = 1};
  {start = "ginzaittyoume"; finish = "yuurakutyou"; transit = "yuurakucyoline"; distance = 0.5; time = 1};
  {start = "yuurakutyou"; finish = "sakuradamon"; transit = "yuurakucyoline"; distance = 1.0; time = 1};
  {start = "sakuradamon"; finish = "nagatacho"; transit = "yuurakucyoline"; distance = 0.9; time = 2};
  {start = "nagatacho"; finish = "koujimachi"; transit = "yuurakucyoline"; distance = 0.9; time = 1};
  {start = "koujimachi"; finish = "ichigaya"; transit = "yuurakucyoline"; distance = 0.9; time = 1};
  {start = "ichigaya"; finish = "idabashi"; transit = "yuurakucyoline"; distance = 1.1; time = 2};
  {start = "idabashi"; finish = "edogawabasi"; transit = "yuurakucyoline"; distance = 1.6; time = 3};
  {start = "edogawabasi"; finish = "gokokuji"; transit = "yuurakucyoline"; distance = 1.3; time = 2};
  {start = "gokokuji"; finish = "higasiikebukuro"; transit = "yuurakucyoline"; distance = 1.1; time = 2};
  {start = "higasiikebukuro"; finish = "ikebukuro"; transit = "yuurakucyoline"; distance = 2.0; time = 2};
  {start = "ikebukuro"; finish = "kanametyou"; transit = "yuurakucyoline"; distance = 1.2; time = 2};
  {start = "kanametyou"; finish = "senkawa"; transit = "yuurakucyoline"; distance = 1.0; time = 1};
  {start = "senkawa"; finish = "kotakemukaihara"; transit = "yuurakucyoline"; distance = 1.0; time = 2};
  {start = "kotakemukaihara"; finish = "hikawadai"; transit = "yuurakucyoline"; distance = 1.5; time = 2};
  {start = "hikawadai"; finish = "heiwadai"; transit = "yuurakucyoline"; distance = 1.4; time = 2};
  {start = "heiwadai"; finish = "eidanakakuka"; transit = "yuurakucyoline"; distance = 1.8; time = 2};
  {start = "eidanakakuka"; finish = "eidannarimasu"; transit = "yuurakucyoline"; distance = 1.5; time = 2};
  {start = "eidannarimasu"; finish = "wakousi"; transit = "yuurakucyoline"; distance = 2.1; time = 3};
]


(*
  #use "stationDistanceData.ml";;

  Result
  -------------------------
  ...
*)
